services:
  catalogdb:
    image: ankane/pgvector:latest
    container_name: catalogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalogdb
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: ["postgres", "-c", "shared_buffers=512MB", "-c", "max_connections=200", "-c", "fsync=off"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d catalogdb"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - eShopNetwork

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --save ""
      - --appendonly no
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - eShopNetwork

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      RABBITMQ_MNESIA_BASE: /var/lib/rabbitmq/mnesia
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "+sbwt none +sbwtdcpu none +sbwtdio none +stbt db"
      RABBITMQ_CTL_ERL_ARGS: "+P 1048576 +K true +A 128"
      RABBITMQ_NODENAME: rabbit@rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - eShopNetwork

  basket-api:
    image: basket-api
    build:
      context: .
      dockerfile: src/Basket.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:5221"
      ConnectionStrings__Redis: redis
      ConnectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672
      Identity__Url: "http://identity-api:5001"
      DOTNET_READYTORUN: 1
      DOTNET_TieredPGO: 1
    ports:
      - "5221:5221"
    volumes:
      - basket-data-protection:/app/keys
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh redis:6379 -- ./wait-for-it.sh rabbitmq:5672 -- dotnet Basket.API.dll"]
    networks:
      - eShopNetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5221/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  catalog-api:
    image: catalog-api
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:80"
      ConnectionStrings__CatalogDB: "Host=catalogdb;Port=5432;Database=catalogdb;User Id=postgres;Password=password;"
      ConnectionStrings__EventBus: "amqp://guest:guest@rabbitmq:5672"
      DOTNET_READYTORUN: 1
      DOTNET_TieredPGO: 1
    depends_on:
      catalogdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5001:80"
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh rabbitmq:5672 -- dotnet Catalog.API.dll"]
    networks:
      - eShopNetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  identity-api:
    image: identity-api
    build:
      context: .
      dockerfile: src/Identity.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:5002"
      ConnectionStrings__IdentityDB: "Server=catalogdb;Port=5432;Database=identitydb;User Id=postgres;Password=password;"
      ConnectionStrings__EventBus: "amqp://guest:guest@rabbitmq:5672"
    ports:
      - "5002:5001"
    depends_on:
      catalogdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh rabbitmq:5672 -- ./wait-for-it.sh catalogdb:5432 -- dotnet Identity.API.dll"]
    networks:
      - eShopNetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  ordering-api:
    image: ordering-api
    build:
      context: .
      dockerfile: src/Ordering.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:8080"
      ConnectionStrings__orderingdb: Host=catalogdb;Port=5432;Database=orderingdb;Username=postgres;Password=password
      ConnectionStrings__EventBus: amqp://guest:guest@rabbitmq:5672
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      Identity__Url: http://identity-api:5001
    ports:
      - "5100:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      catalogdb:
        condition: service_healthy
      identity-api:
        condition: service_healthy
    volumes:
      - ordering-api-keys:/app/keys
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh rabbitmq:5672 -- ./wait-for-it.sh orderingdb:5432 -- ./wait-for-it.sh identity-api:5001 -- dotnet Ordering.API.dll"]
    networks:
      - eShopNetwork
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-processor:
    image: order-processor
    build: 
      context: .
      dockerfile: src/OrderProcessor/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:5200"
      ConnectionStrings__EventBus: "amqp://guest:guest@rabbitmq:5672"
      ConnectionStrings__orderingdb: "Host=catalogdb;Port=5432;Database=orderingdb;Username=postgres;Password=password"
    ports:
      - "5200:5200"
    depends_on:
      rabbitmq:
        condition: service_healthy
      catalogdb:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh rabbitmq:5672 -- ./wait-for-it.sh catalogdb:5432 -- dotnet OrderProcessor.dll"]
    networks:
      - eShopNetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5200/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-processor:
    image: payment-processor
    build: 
      context: .
      dockerfile: src/PaymentProcessor/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__EventBus: "amqp://guest:guest@rabbitmq:5672"
    ports:
      - "5500:5500"
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh", "rabbitmq:5672", "--", "dotnet", "PaymentProcessor.dll"]
    networks:
      - eShopNetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5500/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    

networks:
  eShopNetwork:
    driver: bridge

volumes:
  redis_data:
  pg_data:
  rmq_data:
  basket-data-protection:
  ordering-api-keys:
