# Étape de build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Copie les scripts dans un dossier temporaire
COPY scripts/ /tmp/scripts/
RUN chmod +x /tmp/scripts/wait-for-it.sh


COPY . .   

WORKDIR /app/src/WebApp
RUN dotnet restore "WebApp.csproj"
RUN dotnet build "WebApp.csproj" -c Release -o /app/build

COPY src/WebApp/appsettings.Development.json ./appsettings.Development.json
RUN dotnet publish "WebApp.csproj" -c Release -o /out --no-restore

# Étape runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /out .

COPY src/WebApp/appsettings.Development.json ./appsettings.Development.json

# Copie les scripts depuis le dossier temporaire
COPY --from=build /tmp/scripts/wait-for-it.sh /app/wait-for-it.sh

RUN apt-get update && apt-get install -y curl

RUN chmod +x /app/wait-for-it.sh

EXPOSE 5001

ENTRYPOINT ["dotnet", "WebApp.dll"]